bbs/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'bbs'
urlpatterns = [
    url(r'^$', views.thread_list, name='threads'),
    url(r'^(?P<thread_id>[0-9]+)/$', views.message_list, name='messages'),
    url(r'^new/$', views.new_thread, name='new_thread'),
    url(r'^(?P<thread_id>[0-9]+)/new/$', views.new_message, name='new_message'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/create/$', views.create_user, name='create_user'),
]

srlondon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #url(r'^', include('bbs.urls')),
    url(r'^', include('charsheet.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bbs/models.py
from django.db import models
from django.contrib.auth.models import User


class Thread(models.Model):
    title = models.CharField(max_length=256)
    pub_date = models.DateTimeField(verbose_name='creation date')


class Message(models.Model):
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    text = models.CharField(max_length=1024)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    pub_date = models.DateTimeField(verbose_name='creation date')


class Runner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='uploads')

bbs/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.utils import timezone

from .models import Thread, Message, Runner


class RunnerForm(auth_forms.UserCreationForm):
    avatar = forms.ImageField(label='Avatar', required=False)

    def save(self, commit=True):
        user = super().save(self)
        runner = Runner(user=user, avatar=self.cleaned_data['avatar'])
        if commit:
            runner.save()
        return user


class ThreadForm(forms.ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    class Meta:
        model = Thread
        fields = ('title',)

    def save(self, commit=True):
        thread = forms.ModelForm.save(self, commit=False)
        thread.pub_date = timezone.now()
        thread.save()
        return thread


class MessageForm(forms.ModelForm):
    error_css_class = 'error'
    required_css_class = 'required'

    class Meta:
        model = Message
        fields = ('text',)

    def __init__(self, user, thread, *args, **kwargs):
        self.author = user
        self.thread = thread
        forms.BaseModelForm.__init__(self, *args, **kwargs)

    def save(self, commit=True):
        message = forms.ModelForm.save(self, commit=False)
        message.author = self.author
        message.thread = self.thread
        message.pub_date = timezone.now()
        message.save()
        return message

bbs/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Message, Thread
from .forms import MessageForm, ThreadForm, RunnerForm


@login_required
def thread_list(request, form=None):
    threads = Thread.objects.order_by('pub_date')
    context = {
        'threads': threads,
        'form': ThreadForm() if form is None else form,
    }
    return render(request, 'bbs/threads.html', context)


@login_required
def message_list(request, thread_id, form=None):
    thread = get_object_or_404(Thread, pk=thread_id)
    messages = Message.objects.filter(thread=thread).order_by('pub_date')
    context = {
        'thread': thread,
        'messages': messages,
        'form': MessageForm(request.user, thread) if form is None else form,
    }
    return render(request, 'bbs/messages.html', context)


@login_required
def new_thread(request):
    if request.method == 'POST':
        form = ThreadForm(request.POST)
        if form.is_valid():
            thread = form.save()
            return HttpResponseRedirect(reverse('bbs:messages', args=[thread.pk]))
        else:
            return thread_list(request, form=form)
    else:
        return thread_list(request)


@login_required
def new_message(request, thread_id):
    if request.method == 'POST':
        thread = get_object_or_404(Thread, pk=thread_id)
        form = MessageForm(request.user, thread, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('bbs:messages', args=[thread_id]))
        else:
            return message_list(request, thread_id, form=form)
    else:
        return message_list(request, thread_id)


def create_user(request):
    context = {
        'form': RunnerForm(),
        'next': request.GET.get('next', '/'),
    }
    if request.method == 'POST':
        form = RunnerForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            user = authenticate(username=request.POST["username"], password=request.POST["password1"])
            login(request, user)
            return HttpResponseRedirect(request.POST['next'])
        else:
            context['form'] = form
            return render(request, 'registration/create_user.html', context)
    else:
        return render(request, 'registration/create_user.html', context)

templates/bbs/messages.html
{% extends "base.html" %}

{% block title %}Messages{% endblock %}

{% block content %}
    <span><a href="{% url 'bbs:threads' %}">back to threads</a></span>
    <div id="content">
        <h1>{{ thread.title }}</h1>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>
        <span class="avatar">
        {% if message.author.runner.avatar %}<img src="{{ message.author.runner.avatar.url }}"/>{% endif %}
        </span>
                        {#        <span class="message">#}
                        <strong>{{ message.pub_date }} [{{ message.author.username }}]:</strong>
                        {{ message.text }}
                        {#        </span>#}
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No messages</p>
        {% endif %}
        <form action="{% url 'bbs:new_message' thread.id %}" method="post">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
            <input type="submit" value="New Message"/>
        </form>
    </div>
{% endblock %}

templates/bbs/threads.html
{% extends "base.html" %}

{% block title %}Threads{% endblock %}

{% block content %}
<span>Welcome: {{ user.username }}</span>

<div id="content">
    <h1>Threads</h1>

{% if threads %}
    <ul>
    {% for thread in threads %}
        <li>
        <span>
            <strong>{{ thread.pub_date }}:</strong>&nbsp;<a href="{% url 'bbs:messages' thread.id %}">{{ thread.title }}</a>
        </span>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No threads</p>
{% endif %}
    <form action="{% url 'bbs:new_thread' %}" method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="New Thread"/>
    </form>
</div>
{% endblock %}